website/views.py
from . import db
from flask_login import login_required, current_user
from user_profile_details import github, codechef, codeforces
from .models import Codechef, Codeforces, Friends, Github, User
from flask import Blueprint, flash, redirect, render_template, request, url_for


views = Blueprint("views", __name__)


@views.route("/")
@login_required
def home():
    git = Github.query.filter_by(user_id=current_user.id).first()
    cf = Codeforces.query.filter_by(user_id=current_user.id).first()
    cc = Codechef.query.filter_by(user_id=current_user.id).first()
    return render_template(
        "profile.html", user=current_user, github=git, codechef=cc, codeforces=cf
    )


@views.route("/public_profile", methods=["POST"])
@login_required
def public_profile():
    email = request.form.get("email", "")
    if not email:
        return redirect(url_for("view.home"))

    friend = User.query.filter_by(email=email).first()
    if not friend:
        flash("User does not exist.", category="error")
        return redirect((url_for("views.home")))

    isfriend = bool(
        Friends.query.filter_by(user_id=current_user.id, friend_id=friend.id).first()
    )

    git = Github.query.filter_by(user_id=friend.id).first()
    cf = Codeforces.query.filter_by(user_id=friend.id).first()
    cc = Codechef.query.filter_by(user_id=friend.id).first()

    return render_template(
        "publicprofile.html",
        user=current_user,
        friend=friend,
        isfriend=isfriend,
        github=git,
        codechef=cc,
        codeforces=cf,
    )


@views.route("/leaderboard")
def leaderboard():
    global_leaderboard = get_global_leaderboard()
    friends_leaderboard = get_friend_leaderboard()

    return render_template(
        "leaderboard.html",
        user=current_user,
        global_leaderboard=global_leaderboard,
        friends_leaderboard=friends_leaderboard,
    )


@views.route("/refresh_github", methods=["POST"])
@login_required
def refresh_github():
    git = Github.query.filter_by(user_id=current_user.id)
    github_details = github.fetch_github_data(current_user.github_username)

    git.update(
        {
            "followers": github_details["followers"],
            "public_repos": github_details["public_repos"],
            "total_commits": github_details["total_commits"],
            "stargazers_count": github_details["stargazers_count"],
            "forks_count": github_details["forks_count"],
        }
    )

    try:
        db.session.commit()
        flash("Updated GitHub", category="success")
    except Exception as e:
        flash("Unable to add Github", category="error")

    update_rating()
    return redirect(url_for("views.home"))


@views.route("/refresh_codeforces", methods=["POST"])
@login_required
def refresh_codeforces():
    cf = Codeforces.query.filter_by(user_id=current_user.id)
    codeforces_details = codeforces.fetch_codeforces_data(
        current_user.codeforces_username
    )

    cf.update(
        {
            "rank": codeforces_details["rank"],
            "rating": codeforces_details["rating"],
            "problems_solved": codeforces_details["problems_solved"],
            "contests": codeforces_details["contests"],
            "highest_rating": codeforces_details["highest_rating"],
        }
    )

    try:
        db.session.commit()
        flash("Updated Codeforces", category="success")
    except Exception as e:
        flash("Unable to add Codeforces", category="error")

    update_rating()
    return redirect(url_for("views.home"))


@views.route("/refresh_codechef", methods=["POST"])
@login_required
def refresh_codechef():
    cc = Codechef.query.filter_by(user_id=current_user.id)
    codechef_details = codechef.fetch_codechef_data(current_user.codechef_username)

    cc.update(
        {
            "rating": codechef_details["rating"],
            "solved": codechef_details["solved"],
            "country_rank": codechef_details["country_rank"],
            "global_rank": codechef_details["global_rank"],
            "highest_rating": codechef_details["highest_rating"],
            "num_stars": codechef_details["num_stars"],
            "country": codechef_details["country"],
        }
    )

    try:
        db.session.commit()
        flash("Updated Codechef", category="success")
    except Exception as e:
        flash("Unable to add Codechef", category="error")

    update_rating()
    return redirect(url_for("views.home"))


def get_global_leaderboard():
    leaderboard = []
    for user in User.query.all():
        leaderboard.append((user.full_name, user.email, user.score))
    leaderboard.sort(key=lambda x: x[2], reverse=True)
    return leaderboard


def get_friend_leaderboard():
    leaderboard = [(current_user.full_name, current_user.email, current_user.score)]
    for friend_relation in current_user.friends:
        friend = User.query.get(friend_relation.friend_id)
        leaderboard.append((friend.full_name, friend.email, friend.score))
    leaderboard.sort(key=lambda x: x[2], reverse=True)
    return leaderboard


def update_rating(user=current_user):
    total_rating = user.upvotes - user.downvotes

    if current_user.codechef_username:
        cc = Codechef.query.filter_by(user_id=user.id).first()
        total_rating += cc.rating / 10

    if current_user.codeforces_username:
        cf = Codeforces.query.filter_by(user_id=user.id).first()
        total_rating += cf.rating / 10

    if current_user.github_username:
        git = Github.query.filter_by(user_id=user.id).first()
        total_rating += git.total_commits

    try:
        user.score = total_rating
        db.session.commit()

        flash("Updated rating", category="success")
    except Exception as e:
        flash("Could not update rating", category="error")

website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- CSS Stylesheets -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <!-- Profile page sheets -->
  <!-- <link rel="stylesheet" href="style.css"> -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/css/bootstrap.min.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/js/bootstrap.bundle.min.js">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  <!-- Title of Each Page -->
  {% block head %}
  {% endblock %}

</head>

<body>
  <!-- NavBar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar">
      <div class="navbar-nav">
        {% if user.is_authenticated %}
        <a class="nav-item nav-link" id="home" href="/">Home</a>
        <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
        {% else %}
        <a class="nav-item nav-link" id="login" href="/login">Login</a>
        <a class="nav-item nav-link" id="signUp" href="/signup">Sign Up</a>
        {% endif %}
      </div>
    </div>
  </nav>

  <!-- Flash Messages -->
  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
  {% for category, message in messages %}
  {% if category == 'error' %}
  <div class="alert alert-danger alter-dismissable fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% else %}
  <div class="alert alert-success alter-dismissable fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endif %}
  {% endfor %}
  {% endif %}
  {% endwith %}

  <!-- Content of Each Page -->
  {% block content %}
  {% endblock %}

  <!-- JS Scripts -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
    </script>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
    </script>

</body>

</html>

website/templates/leaderboard.html
{% extends "base.html" %}

{% block head %}
<title>Leaderboard</title>
<link rel="stylesheet" href="{{ url_for('static', filename='css/leaderboard_style.css') }}">
{% endblock %}


{% block content %}
<div class="rating">
    <h2>Personal Ranking</h2>
    <div class="cur_rating">
        <div class="rating_card_common c_rating_head">
            <h3>Name</h3>
            <h3>Email</h3>
            <h3>Score</h3>
        </div>
        {% for user in friends_leaderboard %}
        <div class="rating_card_common c_rating_data">
            <span>{{ user[0] }}</span>
            <form action="{{ url_for('views.public_profile') }}" method="post">
                <button type="submit" name="email" value="{{ user[1] }}">{{ user[1] }}</button>
            </form>
            <span>{{ user[2] }}</span>
        </div>
        {% endfor %}
    </div>

    <h2>Global Rating</h2>
    <div class="global_rating">
        <div class="rating_card_common c_rating_head">
            <h3>Name</h3>
            <h3>Email</h3>
            <h3>Score</h3>
        </div>
        {% for user in global_leaderboard %}
        <div class="rating_card_common c_rating_data">
            <span>{{ user[0] }}</span>
            <form action="{{ url_for('views.public_profile') }}" method="post">
                <button type="submit" name="email" value="{{ user[1] }}">{{ user[1] }}</button>
            </form>
            <span>{{ user[2] }}</span>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}

{% block head %}
<title>Sign In</title>
<link rel="stylesheet" href="{{ url_for('static', filename='css/login_style.css') }}">
{% endblock %}

{% block content %}
    <div class="out_box">
        <div class="in_box">
            <form method="POST">
                <input type="email" class="form-control" id="email" name="email" placeholder="email">
                <input type="password" class="form-control" id="password" name="password" placeholder="password">
                <button type="submit" class="btn">Login</button>
                <span style="margin-top: 30px;">_____________________________</span>
            </form>
            <div class="sign_up">
                <span>Not registered yet? </span><a href="/signup">SIGN UP</a>
            </div>
        </div>
    </div>
{% endblock %}

website/templates/profile.html
{% extends "base.html" %}

{% block head %}
<style>
  .row_new {
    /* border: solid 2px red; */
    height: 100vh;
  }

  .common {
    display: flex;
    padding: 10px 0px 0px 10px;
  }

  .common h6 {
    margin-right: 10px;
  }

  .card_common {
    margin-bottom: 25px;
    border: solid 1.5px lightgray;
    border-radius: 20px 0px 20px 0px;
  }

  .username_common {
    background-color: whitesmoke;
    border-radius: 20px 0px 0px 0px;
  }

  .username_common a {
    text-decoration: none;
    color: black;
    font-weight: 500;
  }

  .username_common img {
    width: 35px;
    margin-bottom: 10px;
    margin-right: 10px;
  }

  .sidebar_logo {
    width: 25px;
  }
</style>
{% endblock %}

{% block content %}
<div class="container">
  <div class="main-body">

    <div class="row gutters-sm">
      <div class="col-md-4 mb-3">
        <div class="card">
          <div class="card-body">
            <div class="d-flex flex-column align-items-center text-center">
              <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle"
                width="150">
              <div class="mt-3">
                <h4>{{ user.full_name }}</h4>
                <p class="text-secondary mb-1">{{ user.occupation }}</p>
              </div>
            </div>
          </div>
        </div>

        <div class="card mt-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
              <img src="../static/image/search.png" alt="Search" class="sidebar_logo">

              <form action="{{ url_for('views.public_profile') }}" method="post">
                <input placeholder="Email..." type="email" id="email" name="email"
                  style="border: solid 1px lightgray;border-radius: 5px;width:79%; margin-left: 20px;">
                <button type="submit" class="btn">Search</button>
              </form>
            </li>

            <li class="list-group-item d-flex justify-content-between align-items-center">
              <img src="../static/image/trophy.png" alt="Search" class="sidebar_logo">
              <div style="width: 100%;margin-left: 30px;">
                <a href="{{ url_for('views.leaderboard') }}" style="text-decoration: none;color: black;font-weight: 500;">Leaderboard</a>
              </div>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <img src="../static/image/logout.png" alt="Search" class="sidebar_logo">
              <div style="width: 100%;margin-left: 30px;">
                <a href="/logout" style="text-decoration: none;color: black;font-weight: 500;">Logout</a>
              </div>
            </li>
          </ul>
        </div>

      </div>
      <div class="col-md-8">

        <div class="row_new">

          <div class="github_card card_common">
            {% if user.github_username %}
            <div class="github_username common username_common">
              <img src="../static/image/github.png" alt="Github">
              <a href="https://github.com/{{ user.github_username }}" target="_blank" rel="noreferrer noopener">
                {{ user.github_username }}</a>
            </div>
            <div class="github_contributions common">
              <h6>Contributions in the Last Year</h6>
              <span>{{ github.total_commits }}</span>
            </div>
            <div class="github_followers common">
              <h6>Total Followers</h6>
              <span>{{ github.followers }}</span>
            </div>
            <div class="github_forks common">
              <h6>Fork Count</h6>
              <span>{{ github.forks_count }}</span>
            </div>
            <div class="github_stars common">
              <h6>Star Count</h6>
              <span>{{ github.stargazers_count }}</span>
            </div>

            <form method="POST" action="{{ url_for('modify.remove_github') }}">
              <button type="submit" class="btn btn-primary">Remove</button>
            </form>

            <form method="POST" action="{{ url_for('views.refresh_github') }}">
              <button type="submit" class="btn btn-primary">Refresh</button>
            </form>

            {% else %}

            <form method="POST" action="{{ url_for('modify.add_github') }}">
              <div class="form-group col-sm-4">
                <label for="github_username">GitHub Username</label>
                <input type="github_username" class="form-control" id="github_username" name="github_username"
                  placeholder="Enter GitHub Username..." />
              </div>
              <br><button type="submit" class="btn btn-primary">Submit</button>
            </form>

            {% endif %}
          </div>

          <div class="cf_card card_common">
            {% if user.codeforces_username %}
            <div class="cf_username common username_common">
              <img src="../static/image/code-forces.png" alt="Codeforces">
              <a href="https://codeforces.com/profile/{{ user.codeforces_username }}" target="_blank"
                rel="noreferrer noopener">{{ user.codeforces_username }}</a>
            </div>
            <div class="cf_u_rating common">
              <h6>Current Rating</h6>
              <span>{{ codeforces.rating }}</span>
            </div>
            <div class="cf_h_rating common">
              <h6>Highest Rating</h6>
              <span>{{ codeforces.highest_rating }}</span>
            </div>
            <div class="cf_contests common">
              <h6>Total Contests</h6>
              <span>{{ codeforces.contests }}</span>
            </div>
            <div class="cf_ps common">
              <h6>Total Problem Solved</h6>
              <span>{{ codeforces.problems_solved }}</span>
            </div>
            <div class="cf_rank common">
              <h6>Current Ranking</h6>
              <span>{{ codeforces.rank }}</span>
            </div>

            <form method="POST" action="{{ url_for('modify.remove_codeforces') }}">
              <button type="submit" class="btn btn-primary">Remove</button>
            </form>

            <form method="POST" action="{{ url_for('views.refresh_codeforces') }}">
              <button type="submit" class="btn btn-primary">Refresh</button>
            </form>

            {% else %}

            <form method="POST" action="{{ url_for('modify.add_codeforces') }}">
              <div class="form-group col-sm-4">
                <label for="codeforces_username">CodeForces Username</label>
                <input type="codeforces_username" class="form-control" id="github_username" name="codeforces_username"
                  placeholder="Enter CodeForces Username..." />
              </div>
              <br><button type="submit" class="btn btn-primary">Submit</button>
            </form>

            {% endif %}
          </div>

          <div class="cc_card card_common">

            {% if user.codechef_username %}

            <div class="cc_username common username_common">
              <img src="../static/image/code-chef.png" alt="CodeChef">
              <a href="https://codechef.com/users/{{ user.codechef_username }}" target="_blank"
                rel="noreferrer noopener">{{ user.codechef_username }}</a>
            </div>
            <div class="cc_country common">
              <h6>Country</h6>
              <span>{{ codechef.country }}</span>
            </div>
            <div class="cc_u_rating common">
              <h6>Current Rating</h6>
              <span>{{ codechef.rating }}</span>
            </div>
            <div class="cc_h_rating common">
              <h6>Highest Rating</h6>
              <span>{{ codechef.highest_rating }}</span>
            </div>
            <div class="cc_global_rank common">
              <h6>Global Ranking</h6>
              <span>{{ codechef.global_rank }}</span>
            </div>
            <div class="cc_country_rank common">
              <h6>Country Ranking</h6>
              <span>{{ codechef.country_rank }}</span>
            </div>
            <div class="cc_star common">
              <h6>Star Rating</h6>
              <span>{{ codechef.num_stars }}</span>
            </div>

            <form method="POST" action="{{ url_for('modify.remove_codechef') }}">
              <button type="submit" class="btn btn-primary">Remove</button>
            </form>

            <form method="POST" action="{{ url_for('views.refresh_codechef') }}">
              <button type="submit" class="btn btn-primary">Refresh</button>
            </form>

            {% else %}

            <form method="POST" action="{{ url_for('modify.add_codechef') }}">
              <div class="form-group col-sm-4">
                <label for="codechef_username">Codechef Username</label>
                <input type="codechef_username" class="form-control" id="codechef_username" name="codechef_username"
                  placeholder="Enter Codechef Username..." />
              </div>
              <br><button type="submit" class="btn btn-primary">Submit</button>
            </form>

            {% endif %}

          </div>
        </div>
      </div>
    </div>

  </div>
</div>
{% endblock %}

website/templates/publicprofile.html
{% extends "base.html" %}

{% block head %}
<style>
  .row_new {
    /* border: solid 2px red; */
    height: 100vh;
  }

  .common {
    display: flex;
    padding: 10px 0px 0px 10px;
  }

  .common h6 {
    margin-right: 10px;
  }

  .card_common {
    margin-bottom: 25px;
    border: solid 1.5px lightgray;
    border-radius: 20px 0px 20px 0px;
  }

  .username_common {
    background-color: whitesmoke;
    border-radius: 20px 0px 0px 0px;
  }

  .username_common a {
    text-decoration: none;
    color: black;
    font-weight: 500;
  }

  .username_common img {
    width: 35px;
    margin-bottom: 10px;
    margin-right: 10px;
  }

  .sidebar_logo {
    width: 25px;
  }
</style>
{% endblock %}

{% block content %}
<div class="container">
  <div class="main-body">

    <div class="row gutters-sm">
      <div class="col-md-4 mb-3">
        <div class="card">
          <div class="card-body">
            <div class="d-flex flex-column align-items-center text-center">
              <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle"
                width="150">
              <div class="mt-3">
                <h4>{{ friend.full_name }}</h4>
                <p class="text-secondary mb-1">{{ friend.occupation }}</p>
                {% if isfriend %}
                <form action="{{ url_for('modify.delete_friend') }}" method="post">
                  <button class="btn btn-primary" name="friend_id" value="{{ friend.id }}">UnFollow</button>
                </form>
                {% else %}
                <form action="{{ url_for('modify.add_friend') }}" method="post">
                  <button class="btn btn-primary" name="friend_id" value="{{ friend.id }}">Follow</button>
                </form>
                {% endif %}
              </div>

              <div>
                <a href="{{ url_for('modify.add_upvote', friend_id=friend.id) }}">
                  <img src="../static/image/thumbd_up.png" alt="Like" style="width:60px">
                </a>

                <a href="{{ url_for('modify.add_downvote', friend_id=friend.id) }}">
                  <img src="../static/image/thumbd_up.png" alt="UnLike"
                    style="width:60px;-webkit-transform:rotate(180deg);-moz-transform: rotate(180deg);-ms-transform: rotate(180deg);-o-transform: rotate(180deg);transform: rotate(180deg);"></a>
              </div>
            </div>
          </div>
        </div>

      </div>
      <div class="col-md-8">

        <div class="row_new">

          <div class="github_card card_common">
            {% if friend.github_username %}
            <div class="github_username common username_common">
              <img src="../static/image/github.png" alt="Github">
              <a href="https://github.com/{{ user.github_username }}" target="_blank" rel="noreferrer noopener">
                {{ friend.github_username }}</a>
            </div>
            <div class="github_contributions common">
              <h6>Contributions in the Last Year</h6>
              <span>{{ github.total_commits }}</span>
            </div>
            <div class="github_followers common">
              <h6>Total Followers</h6>
              <span>{{ github.followers }}</span>
            </div>
            <div class="github_forks common">
              <h6>Fork Count</h6>
              <span>{{ github.forks_count }}</span>
            </div>
            <div class="github_stars common">
              <h6>Star Count</h6>
              <span>{{ github.stargazers_count }}</span>
            </div>

            {% else %}

            <h3>Not Available</h3>

            {% endif %}
          </div>

          <div class="cf_card card_common">
            {% if friend.codeforces_username %}
            <div class="cf_username common username_common">
              <img src="../static/image/code-forces.png" alt="Codeforces">
              <a href="https://codeforces.com/profile/{{ user.codeforces_username }}" target="_blank"
                rel="noreferrer noopener">{{ friend.codeforces_username }}</a>
            </div>
            <div class="cf_u_rating common">
              <h6>Current Rating</h6>
              <span>{{ codeforces.rating }}</span>
            </div>
            <div class="cf_h_rating common">
              <h6>Highest Rating</h6>
              <span>{{ codeforces.highest_rating }}</span>
            </div>
            <div class="cf_contests common">
              <h6>Total Contests</h6>
              <span>{{ codeforces.contests }}</span>
            </div>
            <div class="cf_ps common">
              <h6>Total Problem Solved</h6>
              <span>{{ codeforces.problems_solved }}</span>
            </div>
            <div class="cf_rank common">
              <h6>Current Ranking</h6>
              <span>{{ codeforces.rank }}</span>
            </div>

            {% else %}

            <h3>Not Available</h3>

            {% endif %}
          </div>

          <div class="cc_card card_common">

            {% if user.codechef_username %}

            <div class="cc_username common username_common">
              <img src="../static/image/code-chef.png" alt="CodeChef">
              <a href="https://codechef.com/users/{{ user.codechef_username }}" target="_blank"
                rel="noreferrer noopener">{{ friend.codechef_username }}</a>
            </div>
            <div class="cc_country common">
              <h6>Country</h6>
              <span>{{ codechef.country }}</span>
            </div>
            <div class="cc_u_rating common">
              <h6>Current Rating</h6>
              <span>{{ codechef.rating }}</span>
            </div>
            <div class="cc_h_rating common">
              <h6>Highest Rating</h6>
              <span>{{ codechef.highest_rating }}</span>
            </div>
            <div class="cc_global_rank common">
              <h6>Global Ranking</h6>
              <span>{{ codechef.global_rank }}</span>
            </div>
            <div class="cc_country_rank common">
              <h6>Country Ranking</h6>
              <span>{{ codechef.country_rank }}</span>
            </div>
            <div class="cc_star common">
              <h6>Star Rating</h6>
              <span>{{ codechef.num_stars }}</span>
            </div>

            {% else %}

            <h3>Not Available</h3>

            {% endif %}

          </div>
        </div>


      </div>
    </div>

  </div>
</div>
{% endblock %}

website/templates/signup.html
{% extends "base.html" %}

{% block head %}
<title>Sign Up</title>
<link rel="stylesheet" href="{{ url_for('static', filename='css/signup_style.css') }}">
<!-- <link rel="stylesheet" href="website/static/css/signup_style.css"> -->
{% endblock %}

{% block content %}
    <div class="out_box">
        <div class="in_box">
            <form method="POST">
                <input type="email" class="form-control" id="email" name="email" placeholder="E-mail">
                <input type="text" class="form-control" id="full_name" name="full_name" placeholder="Full Name">
                <select name="gender" class="gender_combo">
                    <option value="">Select Gender</option>
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                    <option value="Non-Binary">Non-Binary</option>
                  </select>
                <input type="text" class="form-control" id="occupation" name="occupation" placeholder="(Optional) Occupation">
                <input type="password" class="form-control" id="password" name="password1" placeholder="Password">
                <input type="password" class="form-control" id="password" name="password2"
                    placeholder="Confirm Password">

                <button type="submit" class="btn">Login</button>
                <span style="margin-top:30px;">_____________________________</span>
            </form>
            <div class="sign_up">
                <span>Already have an account? </span><a href="/login">SIGN IN</a>
            </div>
        </div>
    </div>
{% endblock %}